### ISSUE TITLE
Provide historical context in prologue

### ISSUE THREAD

**Issue by sambacha** [ricobank/ricobank#36]
Rico should have an unofficial prologue providing historical context as to why we are here wrt "legacy financial systems" 

After all, who does not enjoy a good story? (Or to be refreshed with the storyline) 

-----

## Prelude on _Money_

To begin with, a pair of definitions: Credit is the promise to pay money, i.e., debt. Money is that contrivance which discharges debt.

Money is a very long story. From the founding of the Republic until 1971, gold and/or silver were money. Value was intrinsic in them. A dollar was defined as a certain number of grains of fine gold--25.8 grains under the Gold Standard Act of 1900. Paper dollars were exchangeable into gold and derived their value from gold.

The age of paper money dawned in 1971. To the post-1971 dollar, value is imparted, not intrinsic. It is imparted by the words that the Bureau of Engraving and Printing stamps on the face of each unit of green currency: "This note is legal tender for all debts, public and private."

Take pause at the word "note." A note is a credit instrument, a promise to pay. Yet, under law, Federal Reserve notes are money. What is the nature of this promise? The truth is that it is no promise at all, but an artifact from the era of convertibility. Until 1933, $20.67 could be converted into, or redeemed for, one ounce of gold. The dollar was said to be anchored by gold. As there was only so much metal, there could only be so many dollars.

The late John Exter, banker and monetary thinker, acidly described the modern-day Federal Reserve note as an "IOU nothing."

---

**Comment by kbrav** [comment]
Don't think this is what we're going for
