### ISSUE TITLE
What happened to the issues and PRs before the repo was made public?

### ISSUE THREAD

**Issue by sambacha** [ricobank/ricobank#44]
The title says it all, there are references to PR's that do not exist from other repos, etc.

**Comment by sambacha** [comment]
OK, it seems this is a GitHub defect, for example: https://github.com/ricobank/ricobank/pull/77
does not link, however we can search the Git log and find

https://github.com/ricobank/ricobank/commit/114cdf3f592e66be176ee02369defca92bc83d72

> stop occasional test failures due to real time passing (#77)

**Comment by kbrav** [comment]
We deleted the repo and recreated it late last year.
